
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 27 21:36:19 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TWOEQUAL = 5;
  public static final int CONST = 7;
  public static final int NAMESPACE = 33;
  public static final int NOTEQUAL = 6;
  public static final int GREATER = 37;
  public static final int LPAREN = 15;
  public static final int SEMI = 8;
  public static final int CONTINUE = 23;
  public static final int MINUS = 42;
  public static final int LESS = 39;
  public static final int FOR = 27;
  public static final int NUMBERCONST = 34;
  public static final int STATIC = 31;
  public static final int RPAREN = 16;
  public static final int AND = 14;
  public static final int LESSEQUAL = 40;
  public static final int OR = 13;
  public static final int COMMA = 12;
  public static final int DIV = 44;
  public static final int MULTIPLY = 43;
  public static final int PLUS = 41;
  public static final int IF = 20;
  public static final int TWODOT = 19;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int LSBRACE = 10;
  public static final int RETURN = 24;
  public static final int EQUAL = 9;
  public static final int RSBRACE = 11;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MOD = 45;
  public static final int BREAK = 22;
  public static final int IDENT = 32;
  public static final int VOID = 17;
  public static final int GREATEREQUAL = 38;
  public static final int LBRACE = 3;
  public static final int ELSE = 21;
  public static final int READ = 25;
  public static final int CHARCONST = 35;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 36;
  public static final int PROG = 2;
  public static final int TWOMINUS = 29;
  public static final int TWOPLUS = 28;
  public static final int PRINT = 26;
}

